export function categoriesResource(db: any) {
  return {
    resource: db.table('categories'),
    options: {
      navigation: { name: 'Справочники', icon: 'Tag' },
      actions: {
        new: { isAccessible: false },
        edit: { isAccessible: false },
        delete: { isAccessible: false },
      },
      listProperties: ['name', 'slug', 'br', 'target', 'is_default', 'is_active', 'order_index'],
      filterProperties: ['rn', 'br', 'target', 'is_default', 'is_active'],
      showProperties: [
        'id',
        'rn',
        'br',
        'target',
        'category_id',
        'slug',
        'name',
        'parent_id',
        'order_index',
        'classifier_id',
        'is_default',
        'is_active',
        'icon_url',
        'image_url',
        'imported_at',
      ],
      properties: {
        id: { label: 'ID' },
        rn: { label: 'Торговая сеть (rn)' },
        br: { label: 'Город (br)' },
        target: { label: 'Платформа' },
        category_id: { label: 'ID категории (источник)' },
        slug: { label: 'Slug' },
        name: { label: 'Название' },
        parent_id: { label: 'Родитель' },
        order_index: { label: 'Порядок' },
        classifier_id: { label: 'Классификатор' },
        is_default: { label: 'Виртуальная (default)' },
        is_active: { label: 'Активна' },
        icon_url: { label: 'Иконка' },
        image_url: { label: 'Изображение' },
        imported_at: { label: 'Импортировано' },
      },
    },
  };
}
